const loginActionTypes = {
  LOGIN: 'LOGIN',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAIL: 'LOGIN_FAIL',
  CREATE: 'CREATE',
  CREATE_SUCCESS: 'CREATE_SUCCESS',
  CREATE_FAIL: 'CREATE_FAIL',
  VALID_TOKEN: 'VALID_TOKEN',
  INVALID_TOKEN: 'INVALID_TOKEN',
}

export { loginActionTypes }